export const US_CITIES: readonly (readonly [name: string, state: string])[] = [
  ['New York', 'NY'],
  ['Los Angeles', 'CA'],
  ['Chicago', 'IL'],
  ['Houston', 'TX'],
  ['Phoenix', 'AZ'],
  ['Philadelphia', 'PA'],
  ['San Antonio', 'TX'],
  ['San Diego', 'CA'],
  ['Dallas', 'TX'],
  ['Fort Worth', 'TX'],
  ['Jacksonville', 'FL'],
  ['Austin', 'TX'],
  ['San Jose', 'CA'],
  ['Charlotte', 'NC'],
  ['Columbus', 'OH'],
  ['Indianapolis', 'IN'],
  ['San Francisco', 'CA'],
  ['Seattle', 'WA'],
  ['Denver', 'CO'],
  ['Nashville', 'TN'],
  ['Oklahoma City', 'OK'],
  ['Washington', 'DC'],
  ['El Paso', 'TX'],
  ['Las Vegas', 'NV'],
  ['Boston', 'MA'],
  ['Detroit', 'MI'],
  ['Louisville', 'KY'],
  ['Portland', 'OR'],
  ['Memphis', 'TN'],
  ['Baltimore', 'MD'],
  ['Milwaukee', 'WI'],
  ['Albuquerque', 'NM'],
  ['Fresno', 'CA'],
  ['Tucson', 'AZ'],
  ['Sacramento', 'CA'],
  ['Atlanta', 'GA'],
  ['Kansas City', 'MO'],
  ['Mesa', 'AZ'],
  ['Raleigh', 'NC'],
  ['Colorado Springs', 'CO'],
  ['Miami', 'FL'],
  ['Omaha', 'NE'],
  ['Virginia Beach', 'VA'],
  ['Long Beach', 'CA'],
  ['Oakland', 'CA'],
  ['Minneapolis', 'MN'],
  ['Bakersfield', 'CA'],
  ['Tulsa', 'OK'],
  ['Tampa', 'FL'],
  ['Aurora', 'CO'],
  ['Arlington', 'TX'],
  ['Wichita', 'KS'],
  ['Cleveland', 'OH'],
  ['New Orleans', 'LA'],
  ['Henderson', 'NV'],
  ['Honolulu', 'HI'],
  ['Anaheim', 'CA'],
  ['Orlando', 'FL'],
  ['Lexington', 'KY'],
  ['Stockton', 'CA'],
  ['Newark', 'NJ'],
  ['Riverside', 'CA'],
  ['Irvine', 'CA'],
  ['Corpus Christi', 'TX'],
  ['Santa Ana', 'CA'],
  ['Cincinnati', 'OH'],
  ['Greensboro', 'NC'],
  ['Pittsburgh', 'PA'],
  ['St. Paul', 'MN'],
  ['Durham', 'NC'],
  ['Jersey City', 'NJ'],
  ['Lincoln', 'NE'],
  ['North Las Vegas', 'NV'],
  ['Plano', 'TX'],
  ['Gilbert', 'AZ'],
  ['Anchorage', 'AK'],
  ['Madison', 'WI'],
  ['Reno', 'NV'],
  ['Chandler', 'AZ'],
  ['St. Louis', 'MO'],
  ['Chula Vista', 'CA'],
  ['Fort Wayne', 'IN'],
  ['Buffalo', 'NY'],
  ['Lubbock', 'TX'],
  ['Laredo', 'TX'],
  ['Port St. Lucie', 'FL'],
  ['St. Petersburg', 'FL'],
  ['Toledo', 'OH'],
  ['Glendale', 'AZ'],
  ['Winston-Salem', 'NC'],
  ['Irving', 'TX'],
  ['Chesapeake', 'VA'],
  ['Garland', 'TX'],
  ['Scottsdale', 'AZ'],
  ['Boise', 'ID'],
  ['Richmond', 'VA'],
  ['Frisco', 'TX'],
  ['Cape Coral', 'FL'],
  ['McKinney', 'TX'],
  ['Huntsville', 'AL'],
] as const
